version: "2"

services:
  zeebe:
    logging:
      driver: none
    container_name: zeebe_broker
    image: camunda/zeebe:8.1.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_NETWORK_HOST=0.0.0.0
      - ZEEBE_BROKER_GATEWAY_SECURITY_ENABLED=true
      - ZEEBE_BROKER_GATEWAY_SECURITY_CERTIFICATECHAINPATH=/usr/local/zeebe/cert.pem
      - ZEEBE_BROKER_GATEWAY_SECURITY_PRIVATEKEYPATH=/usr/local/zeebe/key.pem
    volumes:
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
      - ./cert/cert.pem:/usr/local/zeebe/cert.pem
      - ./cert/key.pem:/usr/local/zeebe/key.pem
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:9600/actuator/health" ]
      interval: 5s
      timeout: 15s
      retries: 30
      start_period: 60s
    ports:
      - "26500:26500"
    networks:
      - test
  zbctl-test:
    links:
      - "zeebe:test.test.localhost"
    image: node:16-alpine
    depends_on:
      zeebe:
        condition: service_healthy
    environment:
      - ZEEBE_ADDRESS=test.test.localhost:26500
      - ZEEBE_INSECURE_CONNECTION=false
      - ZEEBE_CA_CERTIFICATE_PATH=/usr/local/zeebe/rootCA.crt
    command: sh -c "ping test.test.localhost -c 1 && npm install -g zbctl && zbctl status"
    volumes:
      - ./cert/rootCA.crt:/usr/local/zeebe/rootCA.crt
    networks:
      - test
  zebee-node-test:
    links:
      - "zeebe:test.test.localhost"
    image: node:16-alpine
    depends_on:
      zeebe:
        condition: service_healthy
    environment:
      - ZEEBE_ADDRESS=test.test.localhost:26500
      - ZEEBE_INSECURE_CONNECTION=false
      - ZEEBE_CA_CERTIFICATE_PATH=/usr/local/zeebe/rootCA.crt
      - LOG_LEVEL=debug
      - GRPC_VERBOSITY=DEBUG
      - GRPC_TRACE=channel,subchannel,call_stream
    command: sh -c "ping test.test.localhost -c 1 && cd /usr/local/zeebe && npm install zeebe-node && node index.js"
    volumes:
      - ./cert/rootCA.crt:/usr/local/zeebe/rootCA.crt
      - ./index.js:/usr/local/zeebe/index.js
    networks:
      - test

networks:
  test: