version: "2"

services:
  nginx:
    container_name: nginx
    image: jwilder/nginx-proxy:1.3
    healthcheck:
      test: 'echo Running'
      interval: 30s
      timeout: 15s
      retries: 5
    ports:
      - ${NGINX_PORT:-443}:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./cert:/etc/nginx/certs
    networks:
      - test
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:${ZEEBE_VERSION:-8.1.0}
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_NETWORK_HOST=0.0.0.0
      - ZEEBE_BROKER_GATEWAY_SECURITY_ENABLED=${ZEEBE_BROKER_GATEWAY_SECURITY_ENABLED:-true}
      - ZEEBE_BROKER_GATEWAY_SECURITY_CERTIFICATECHAINPATH=/usr/local/zeebe/server.crt
      - ZEEBE_BROKER_GATEWAY_SECURITY_PRIVATEKEYPATH=/usr/local/zeebe/server.pem
      - ZEEBE_BROKER_GATEWAY_NETWORK_PORT=${ZEEBE_PORT:-26500}
      - VIRTUAL_HOST=${ZEEBE_HOSTNAME:-sub.example.com}
      - VIRTUAL_PORT=${ZEEBE_PORT:-26500}
      - VIRTUAL_PROTO=grpc
    volumes:
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
      - ./cert/server.crt:/usr/local/zeebe/server.crt
      - ./cert/server.pem:/usr/local/zeebe/server.pem
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:9600/actuator/health" ]
      interval: 5s
      timeout: 15s
      retries: 30
      start_period: 60s
    ports:
      - "${ZEEBE_PORT:-26500}:${ZEEBE_PORT:-26500}"
    networks:
      - test
  zbctl-test:
    links:
      - "zeebe:${ZEEBE_HOSTNAME:-sub.example.com}"
    image: node:16-alpine
    depends_on:
      zeebe:
        condition: service_healthy
    environment:
      - ZEEBE_ADDRESS=${ZEEBE_HOSTNAME:-sub.example.com}:${ZEEBE_PORT:-26500}
      - ZEEBE_INSECURE_CONNECTION=${ZEEBE_INSECURE_CONNECTION:-false}
      - ZEEBE_CA_CERTIFICATE_PATH=/usr/local/zeebe/root.crt
    command: sh -c "ping ${ZEEBE_HOSTNAME:-sub.example.com} -c 1 && npx zbctl status -o json"
    volumes:
      - ./cert/root.crt:/usr/local/zeebe/root.crt
    networks:
      - test
  zebee-node-test:
    links:
      - "zeebe:${ZEEBE_HOSTNAME:-sub.example.com}"
    image: node:16-alpine
    depends_on:
      zeebe:
        condition: service_healthy
    environment:
      - ZEEBE_ADDRESS=${ZEEBE_HOSTNAME:-sub.example.com}:${ZEEBE_PORT:-26500}
      - ZEEBE_INSECURE_CONNECTION=${ZEEBE_INSECURE_CONNECTION:-false}
      - ZEEBE_CA_CERTIFICATE_PATH=/usr/local/zeebe/root.crt
      - LOG_LEVEL=debug
      - GRPC_VERBOSITY=DEBUG
      - GRPC_TRACE=channel,subchannel,call_stream
    command: sh -c "ping ${ZEEBE_HOSTNAME:-sub.example.com} -c 1 && cd /usr/local/zeebe && node index.js"
    volumes:
      - ./cert/root.crt:/usr/local/zeebe/root.crt
      - ./index.js:/usr/local/zeebe/index.js
      - ./node_modules:/usr/local/zeebe/node_modules
    networks:
      - test

networks:
  test: