name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

env:
  COMMON_NAME: example.com
  ZEEBE_HOSTNAME: test.example.com
  ZEEBE_ADDRESS: test.example.com:26500
  NGINX_PORT: 443

jobs:
  build:
    strategy:
      matrix:
        zeebeVersion: [8.1.0, 8.2.2]
    runs-on: ubuntu-latest
    env:
      ZEEBE_VERSION: ${{ matrix.zeebeVersion }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: Setup hosts
      run: sh -c 'echo "127.0.0.1    $ZEEBE_HOSTNAME"' | sudo tee -a /etc/hosts
    - name: Generate certificates
      run: npm run generate-certs

    - name: Create Zebee container (secure)
      env:
        ZEEBE_VERSION: ${{ matrix.zeebeVersion }}
      run: docker-compose up --no-start zeebe
    - name: Start Zebee (secure)
      run: docker-compose up --detach zeebe
    - name: Sleep for 10 seconds
      run: sleep 10s
    - name: Test (secure)
      run: |
        npm run test:secure | tee output.txt
        results=$(grep "\"gatewayVersion\": \"${ZEEBE_VERSION}\"" -c output.txt)
        if [[ "$results" != "2" ]]; then
          echo "missing <gatewayVersion>"
          exit 1
        fi
    - name: Stop Zeebe (secure)
      run: docker-compose down

    - name: Copy certs for nginx reverse proxy
      run: |
        cp ./cert/server.key ./cert/${{env.ZEEBE_HOSTNAME}}.key
        cp ./cert/server.crt ./cert/${{env.ZEEBE_HOSTNAME}}.crt
    - name: Create Zebee container (secure with nginx reverse proxy)
      run: docker-compose --env-file ./.env.nginx up --no-start zeebe nginx
    - name: Start Zebee (secure with nginx reverse proxy)
      run: docker-compose --env-file ./.env.nginx up --detach zeebe nginx
    - name: Sleep for 10 seconds
      run: sleep 10s
    - name: Test (secure with nginx reverse proxy)
      env:
        ZEEBE_ADDRESS: ${{env.ZEEBE_HOSTNAME}}:${{env.NGINX_PORT}}
      run: |
        npm run test:secure | tee output.txt
        results=$(grep "\"gatewayVersion\": \"${ZEEBE_VERSION}\"" -c output.txt)
        if [[ "$results" != "2" ]]; then
          echo "missing <gatewayVersion>"
          exit 1
        fi
    - name: Stop Zeebe (secure with nginx reverse proxy)
      run: docker-compose down
    - name: Clean up certs of nginx reverse proxy
      run: |
        rm ./cert/${{env.ZEEBE_HOSTNAME}}.key ./cert/${{env.ZEEBE_HOSTNAME}}.crt

    - name: Create Zeebe container (insecure)
      run: docker-compose --env-file ./.env.insecure up --no-start zeebe
    - name: Start Zebee (insecure)
      run: docker-compose --env-file ./.env.insecure up --detach zeebe
    - name: Sleep for 10 seconds
      run: sleep 10s
    - name: Test (insecure)
      run: |
        npm run test:insecure | tee output.txt
        results=$(grep "\"gatewayVersion\": \"${ZEEBE_VERSION}\"" -c output.txt)
        if [[ "$results" != "2" ]]; then
          echo "missing <gatewayVersion>"
          exit 1
        fi
    - name: Stop Zeebe (insecure)
      run: docker-compose down

    - name: Collect docker logs
      if: failure()
      uses: jwalton/gh-docker-logs@v2
      with:
        dest: ./logs
    - name: Upload logs to GitHub
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: docker-compose-logs
        path: ./logs
