name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

env:
  COMMON_NAME: example.com
  ZEEBE_HOST: test.example.com
  ZEEBE_ADDRESS: test.example.com:26500

jobs:
  build:
    strategy:
      matrix:
        zeebeVersion: [8.1.0, 8.2.2]
    runs-on: ubuntu-latest
    env:
      ZEEBE_VERSION: ${{ matrix.zeebeVersion }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: Setup hosts
      run: sh -c 'echo "127.0.0.1    $ZEEBE_HOST"' | sudo tee -a /etc/hosts
    - name: Generate certificates
      run: npm run generate-certs

    - name: Create Zebee container (secure)
      env:
        ZEEBE_VERSION: ${{ matrix.zeebeVersion }}
      run: docker-compose up --no-start zeebe
    - name: Start Zebee (secure)
      run: docker-compose up --detach zeebe
    - name: Sleep for 10 seconds
      run: sleep 10s
    - name: Test (secure)
      run: |
        npm run test:secure | tee output.txt
        results=$(grep "\"gatewayVersion\": \"${ZEEBE_VERSION}\"" -c output.txt)
        if [[ "$results" != "2" ]]; then
          echo "missing <gatewayVersion>"
          exit 1
        fi
    - name: Stop Zeebe (secure)
      run: docker-compose down

    - name: Create Zeebe container (insecure)
      run: docker-compose --env-file ./.env.insecure up --no-start zeebe
    - name: Start Zebee (insecure)
      run: docker-compose --env-file ./.env.insecure up --detach zeebe
    - name: Sleep for 10 seconds
      run: sleep 10s
    - name: Test (insecure)
      run: |
        npm run test:insecure | tee output.txt
        results=$(grep "\"gatewayVersion\": \"${ZEEBE_VERSION}\"" -c output.txt)
        if [[ "$results" != "2" ]]; then
          echo "missing <gatewayVersion>"
          exit 1
        fi
    - name: Stop Zeebe (insecure)
      run: docker-compose down